services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - internal

  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - internal
    volumes:
      - ./backend/app/uploads:/app/uploads
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=admin_mesa
      - POSTGRES_PASSWORD=3MtmNv43A3
      - POSTGRES_DB=mesa_db
    ports:
      - "5432:5432"
    volumes:
      - vol_mesa_final:/var/lib/postgresql/data
    networks:
      - internal
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    command: redis-server --appendonly yes
    networks:
      - internal

networks:
  internal:

volumes:
  vol_mesa_final: